### ISSUE TITLE
rbl nano gcc compile custom_board.h not found

### ISSUE THREAD

**Issue by holla2040** [electronut/nRF51-adc-test#1]
ubuntu 14.04
nRF51_SDK_8.1.0_b6ed55f.zip
gcc version 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 224288]

cd /tmp/nRF51-adc-test/rbl_nano/s110/armgcc
holla@hendrix[621]: make
rm -rf _build _.jlink
echo  Makefile
Makefile
mkdir _build
Compiling file: app_button.c
Compiling file: app_error.c
Compiling file: app_fifo.c
Compiling file: app_timer.c
Compiling file: app_trace.c
Compiling file: nrf_assert.c
Compiling file: retarget.c
Compiling file: app_uart_fifo.c
Compiling file: nrf_delay.c
Compiling file: nrf_adc.c
Compiling file: nrf_drv_common.c
Compiling file: nrf_drv_gpiote.c
Compiling file: pstorage.c
Compiling file: bsp.c
In file included from /tmp/n/examples/bsp/bsp.h:33:0,
                 from /tmp/n/examples/bsp/bsp.c:13:
/tmp/n/examples/bsp/boards.h:36:28: fatal error: custom_board.h: No such file or directory
   #include "custom_board.h"
                            ^
compilation terminated.
make: *_\* [_build/bsp.o] Error 1

arm-gcc compiles pca10028 fine.

**Comment by electronut** [comment]
You have to create custom_board.h and add it to the SDK directory. See:

http://electronut.in/nrf51-dk-external-programming/

**Comment by holla2040** [comment]
thanks for the link. I need to check all your postings.
