### ISSUE TITLE
I want to program for nRF51 (PCA10028)

### ISSUE THREAD

**Issue by NoWayBg** [electronut/nRF51-adc-test#2]
Hello Mahesh Venkitachalam
I have one board Nordic nRF51 KIT, and I want to know can what can I use it to do?
Can I use it to control simple LED (same as microcontroller)

**Comment by electronut** [comment]
Yes, it can do pretty much anything that an ARM Cortex-M controller does. Please take a look at the Nordic nRF5 SDK at:

http://infocenter.nordicsemi.com/index.jsp

You can also see the Nordic projects on my blog. If you are looking to upgrade to nRF52, we have a good development board:

https://www.tindie.com/stores/ElectronutLabs/
